ignoreWorkspaceRootCheck: true

minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - "@yuku-core/binding-android-arm64@0.17.0"
  - "@yuku-core/binding-darwin-arm64@0.17.0"
  - "@yuku-core/binding-darwin-x64@0.17.0"
  - "@yuku-core/binding-freebsd-x64@0.17.0"
  - "@yuku-core/binding-linux-arm-gnu@0.17.0"
  - "@yuku-core/binding-linux-arm-musl@0.17.0"
  - "@yuku-core/binding-linux-arm64-gnu@0.17.0"
  - "@yuku-core/binding-linux-arm64-musl@0.17.0"
  - "@yuku-core/binding-linux-x64-gnu@0.17.0"
  - "@yuku-core/binding-linux-x64-musl@0.17.0"
  - "@yuku-core/binding-win32-arm64@0.17.0"
  - "@yuku-core/binding-win32-x64@0.17.0"
  - "@yuku-toolchain/types@0.17.0"
  - yuku-core@0.17.0
  - yuku-parser@0.17.0

trustPolicy: no-downgrade
trustPolicyExclude:
  - why-is-node-running@3.2.2

update:
  ignoreDeps:
    - typescript@7

shellEmulator: true

packages:
  - "!vendor/*"

overrides:
  array-includes: "npm:@nolyfill/array-includes@latest"
  array.prototype.findlastindex: "npm:@nolyfill/array.prototype.findlastindex@latest"
  array.prototype.flat: "npm:@nolyfill/array.prototype.flat@latest"
  array.prototype.flatmap: "npm:@nolyfill/array.prototype.flatmap@latest"
  hasown: "npm:@nolyfill/hasown@latest"
  object.fromentries: "npm:@nolyfill/object.fromentries@latest"
  object.groupby: "npm:@nolyfill/object.groupby@latest"
  object.values: "npm:@nolyfill/object.values@latest"

  source-map: "npm:source-map-js@latest"

allowBuilds:
  esbuild: true
  simple-git-hooks: true
